# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.action_set import ActionSet
from openapi_server.models.progress_item import ProgressItem
from openapi_server import util

from openapi_server.models.action_set import ActionSet  # noqa: E501
from openapi_server.models.progress_item import ProgressItem  # noqa: E501

class Exercise(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, actions=None, goals=None):  # noqa: E501
        """Exercise - a model defined in OpenAPI

        :param actions: The actions of this Exercise.  # noqa: E501
        :type actions: ActionSet
        :param goals: The goals of this Exercise.  # noqa: E501
        :type goals: List[ProgressItem]
        """
        self.openapi_types = {
            'actions': ActionSet,
            'goals': List[ProgressItem]
        }

        self.attribute_map = {
            'actions': 'actions',
            'goals': 'goals'
        }

        self._actions = actions
        self._goals = goals

    @classmethod
    def from_dict(cls, dikt) -> 'Exercise':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Exercise of this Exercise.  # noqa: E501
        :rtype: Exercise
        """
        return util.deserialize_model(dikt, cls)

    @property
    def actions(self):
        """Gets the actions of this Exercise.


        :return: The actions of this Exercise.
        :rtype: ActionSet
        """
        return self._actions

    @actions.setter
    def actions(self, actions):
        """Sets the actions of this Exercise.


        :param actions: The actions of this Exercise.
        :type actions: ActionSet
        """

        self._actions = actions

    @property
    def goals(self):
        """Gets the goals of this Exercise.


        :return: The goals of this Exercise.
        :rtype: List[ProgressItem]
        """
        return self._goals

    @goals.setter
    def goals(self, goals):
        """Sets the goals of this Exercise.


        :param goals: The goals of this Exercise.
        :type goals: List[ProgressItem]
        """

        self._goals = goals
