# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.basic_action import BasicAction
from openapi_server import util

from openapi_server.models.basic_action import BasicAction  # noqa: E501

class Exercise(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, steps=None):  # noqa: E501
        """Exercise - a model defined in OpenAPI

        :param id: The id of this Exercise.  # noqa: E501
        :type id: int
        :param name: The name of this Exercise.  # noqa: E501
        :type name: str
        :param steps: The steps of this Exercise.  # noqa: E501
        :type steps: List[BasicAction]
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'steps': List[BasicAction]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'steps': 'steps'
        }

        self._id = id
        self._name = name
        self._steps = steps

    @classmethod
    def from_dict(cls, dikt) -> 'Exercise':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Exercise of this Exercise.  # noqa: E501
        :rtype: Exercise
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this Exercise.


        :return: The id of this Exercise.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Exercise.


        :param id: The id of this Exercise.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this Exercise.


        :return: The name of this Exercise.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Exercise.


        :param name: The name of this Exercise.
        :type name: str
        """

        self._name = name

    @property
    def steps(self):
        """Gets the steps of this Exercise.


        :return: The steps of this Exercise.
        :rtype: List[BasicAction]
        """
        return self._steps

    @steps.setter
    def steps(self, steps):
        """Sets the steps of this Exercise.


        :param steps: The steps of this Exercise.
        :type steps: List[BasicAction]
        """

        self._steps = steps
