# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class KPI(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, meaning=None):  # noqa: E501
        """KPI - a model defined in OpenAPI

        :param id: The id of this KPI.  # noqa: E501
        :type id: int
        :param name: The name of this KPI.  # noqa: E501
        :type name: str
        :param meaning: The meaning of this KPI.  # noqa: E501
        :type meaning: str
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'meaning': str
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'meaning': 'meaning'
        }

        self._id = id
        self._name = name
        self._meaning = meaning

    @classmethod
    def from_dict(cls, dikt) -> 'KPI':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The KPI of this KPI.  # noqa: E501
        :rtype: KPI
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self):
        """Gets the id of this KPI.


        :return: The id of this KPI.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this KPI.


        :param id: The id of this KPI.
        :type id: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this KPI.


        :return: The name of this KPI.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this KPI.


        :param name: The name of this KPI.
        :type name: str
        """

        self._name = name

    @property
    def meaning(self):
        """Gets the meaning of this KPI.


        :return: The meaning of this KPI.
        :rtype: str
        """
        return self._meaning

    @meaning.setter
    def meaning(self, meaning):
        """Sets the meaning of this KPI.


        :param meaning: The meaning of this KPI.
        :type meaning: str
        """

        self._meaning = meaning
