# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.kpi import KPI
from openapi_server import util

from openapi_server.models.kpi import KPI  # noqa: E501

class ProgressItem(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, delta=None, measurement=None):  # noqa: E501
        """ProgressItem - a model defined in OpenAPI

        :param delta: The delta of this ProgressItem.  # noqa: E501
        :type delta: float
        :param measurement: The measurement of this ProgressItem.  # noqa: E501
        :type measurement: KPI
        """
        self.openapi_types = {
            'delta': float,
            'measurement': KPI
        }

        self.attribute_map = {
            'delta': 'delta',
            'measurement': 'measurement'
        }

        self._delta = delta
        self._measurement = measurement

    @classmethod
    def from_dict(cls, dikt) -> 'ProgressItem':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProgressItem of this ProgressItem.  # noqa: E501
        :rtype: ProgressItem
        """
        return util.deserialize_model(dikt, cls)

    @property
    def delta(self):
        """Gets the delta of this ProgressItem.


        :return: The delta of this ProgressItem.
        :rtype: float
        """
        return self._delta

    @delta.setter
    def delta(self, delta):
        """Sets the delta of this ProgressItem.


        :param delta: The delta of this ProgressItem.
        :type delta: float
        """

        self._delta = delta

    @property
    def measurement(self):
        """Gets the measurement of this ProgressItem.


        :return: The measurement of this ProgressItem.
        :rtype: KPI
        """
        return self._measurement

    @measurement.setter
    def measurement(self, measurement):
        """Sets the measurement of this ProgressItem.


        :param measurement: The measurement of this ProgressItem.
        :type measurement: KPI
        """

        self._measurement = measurement
