# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class State(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, quality=None, quantity=None):  # noqa: E501
        """State - a model defined in OpenAPI

        :param quality: The quality of this State.  # noqa: E501
        :type quality: str
        :param quantity: The quantity of this State.  # noqa: E501
        :type quantity: int
        """
        self.openapi_types = {
            'quality': str,
            'quantity': int
        }

        self.attribute_map = {
            'quality': 'quality',
            'quantity': 'quantity'
        }

        self._quality = quality
        self._quantity = quantity

    @classmethod
    def from_dict(cls, dikt) -> 'State':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The State of this State.  # noqa: E501
        :rtype: State
        """
        return util.deserialize_model(dikt, cls)

    @property
    def quality(self):
        """Gets the quality of this State.


        :return: The quality of this State.
        :rtype: str
        """
        return self._quality

    @quality.setter
    def quality(self, quality):
        """Sets the quality of this State.


        :param quality: The quality of this State.
        :type quality: str
        """

        self._quality = quality

    @property
    def quantity(self):
        """Gets the quantity of this State.


        :return: The quantity of this State.
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this State.


        :param quantity: The quantity of this State.
        :type quantity: int
        """

        self._quantity = quantity
